In [1]:
import tensorflow as tf

# Creando tensores
t0 = tf.constant(5)                         # Escalar
t1 = tf.constant([1, 2, 3])                # Vector
t2 = tf.constant([[1, 2], [3, 4]])         # Matriz
t3 = tf.constant([
    [[1],[2]],
    [[3],[4]]
])                                         # Tensor 3D

print(t0)
print(t1)
print(t2)
print(t3)


tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [2]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(a + b)      # Suma
print(a * b)      # Multiplicación elemento a elemento
print(tf.matmul([[1,2]], [[3],[4]]))  # Multiplicación matricial


tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([[11]], shape=(1, 1), dtype=int32)


In [3]:
W = tf.Variable(3.0)
b = tf.Variable(1.0)

print(W, b)

# Actualizar valores
W.assign(4.0)
b.assign_add(2.0)

print(W, b)


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>


In [4]:
x = tf.constant(2.0)
W = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = W * x
    loss = (y - 10)**2

grad = tape.gradient(loss, W)
print("gradiente:", grad)


gradiente: tf.Tensor(-16.0, shape=(), dtype=float32)
