In [1]:
import tensorflow as ts
import numpy as np

In [2]:
#Variables
a = ts.constant([1,2,3],dtype=ts.int32)
b = ts.constant([[1,2,3],[4,5,6]],dtype=ts.uint32)
c = ts.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=ts.float64)
print(a)
print(b)
print(c)
d = ts.constant([True,False,True,False],dtype=ts.bool)
print(d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=uint32)
tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float64)
tf.Tensor([ True False  True False], shape=(4,), dtype=bool)


In [3]:
#Convertir de arreglo a tensor
npa = np.array([[8,54,865],[974,98,987]])
e = ts.convert_to_tensor(npa)
print(e)

tf.Tensor(
[[  8  54 865]
 [974  98 987]], shape=(2, 3), dtype=int64)


In [4]:
#Matriz identidad
matriz_identidad = ts.eye(num_rows=5)
print(matriz_identidad)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [5]:
escalar = 5
print(matriz_identidad*escalar)

tf.Tensor(
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]], shape=(5, 5), dtype=float32)


In [6]:
#Tensor rellenada
f = ts.fill(dims=[4,5],value="Cadena")
print(f)

tf.Tensor(
[[b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']], shape=(4, 5), dtype=string)


In [7]:
#Tensor random con funcion normal
g = ts.random.normal([4,4],mean=50.0,stddev=20.0,dtype=ts.dtypes.float16,seed=None,name=None)
print(g)

tf.Tensor(
[[81.6  51.2  34.7  31.97]
 [70.9  34.7  89.6  72.  ]
 [33.62 30.84 52.34 44.56]
 [49.   70.4  67.4  87.1 ]], shape=(4, 4), dtype=float16)


In [8]:
#Tensor random con funcion unfiorme
h = ts.random.uniform([3,3,4],minval=-10.0,maxval=-9.0,dtype=ts.dtypes.float16,seed=None,name=None)
print(h)

tf.Tensor(
[[[ -9.8    -9.56   -9.97   -9.61 ]
  [ -9.164  -9.78   -9.45   -9.67 ]
  [ -9.59   -9.914  -9.83   -9.18 ]]

 [[ -9.695  -9.42   -9.86   -9.69 ]
  [ -9.38   -9.41   -9.31   -9.47 ]
  [ -9.49   -9.54   -9.28   -9.7  ]]

 [[ -9.52   -9.     -9.32   -9.664]
  [-10.     -9.95   -9.11   -9.195]
  [ -9.69   -9.66   -9.07   -9.52 ]]], shape=(3, 3, 4), dtype=float16)
