In [1]:
import tensorflow as ts
import numpy as np

In [2]:
#Variables
a = ts.constant([1,2,3],dtype=ts.int32)
b = ts.constant([[1,2,3],[4,5,6]],dtype=ts.uint32)
c = ts.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=ts.float64)
print(a)
print(b)
print(c)
d = ts.constant([True,False,True,False],dtype=ts.bool)
print(d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=uint32)
tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float64)
tf.Tensor([ True False  True False], shape=(4,), dtype=bool)


In [3]:
#Convertir de arreglo a tensor
npa = np.array([[8,54,865],[974,98,987]])
e = ts.convert_to_tensor(npa)
print(e)

tf.Tensor(
[[  8  54 865]
 [974  98 987]], shape=(2, 3), dtype=int64)


In [4]:
#Matriz identidad
matriz_identidad = ts.eye(num_rows=5)
print(matriz_identidad)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [5]:
escalar = 5
print(matriz_identidad*escalar)

tf.Tensor(
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]], shape=(5, 5), dtype=float32)


In [6]:
#Tensor rellenada
f = ts.fill(dims=[4,5],value="Cadena")
print(f)

tf.Tensor(
[[b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']
 [b'Cadena' b'Cadena' b'Cadena' b'Cadena' b'Cadena']], shape=(4, 5), dtype=string)


In [45]:
#Tensor random con funcion normal
g = ts.random.normal([4,4],mean=50.0,stddev=0.1,dtype=ts.dtypes.float16,seed=None,name=None)
print(g)

tf.Tensor(
[[50.06 50.03 49.94 49.84]
 [49.9  50.1  50.03 50.06]
 [50.   49.94 50.06 50.06]
 [49.94 49.88 50.06 49.84]], shape=(4, 4), dtype=float16)


In [32]:
#Tensor random con funcion unfiorme
h = ts.random.uniform([3,3,4],minval=-10.0,maxval=-9.0,dtype=ts.dtypes.float16,seed=None,name=None)
print(h)

tf.Tensor(
[[[-10.     -9.586  -9.87   -9.03 ]
  [ -9.7   -10.     -9.22   -9.336]
  [ -9.89   -9.51   -9.04   -9.78 ]]

 [[ -9.36   -9.86   -9.336  -9.46 ]
  [ -9.8    -9.35   -9.33   -9.16 ]
  [ -9.31   -9.766  -9.14   -9.516]]

 [[ -9.16   -9.08   -9.72   -9.125]
  [ -9.305  -9.914  -9.48   -9.86 ]
  [ -9.195  -9.2    -9.195  -9.58 ]]], shape=(3, 3, 4), dtype=float16)
