In [6]:
import tensorflow as tf

In [7]:
#Es un tensor donde la mayoria de los valores son cero
st = tf.sparse.SparseTensor(indices=[[0, 0], [1, 1], [2, 2]], values=[1, 2, 3], dense_shape=[3, 3])
print(tf.sparse.to_dense(st))

tf.Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int32)
