In [1]:
arreglo = [1, 2, 3, 4, 5]

In [2]:
import numpy as np

In [3]:
arr = np.array(arreglo)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arreglob = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arrb = np.array(arreglob)

In [7]:
arrb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10)
np.arange(0,20)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])